name: Validate HACS

on:
  push:
    paths:
      - "custom_components/**"
      - "hacs.json"
  pull_request:
    paths:
      - "custom_components/**"
      - "hacs.json"
  workflow_dispatch:

jobs:
  validate-hacs:
    runs-on: ubuntu-latest
    name: Validate HACS
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration

  validate-hassfest:
    runs-on: ubuntu-latest
    name: Validate with hassfest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: hassfest Validation
        uses: home-assistant/actions/hassfest@master
